"""Add full ecosystem models

Revision ID: 230b54e56456
Revises: 5f4cf88051b8
Create Date: 2026-06-18 14:38:58.237314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '230b54e56456'
down_revision: Union[str, None] = '5f4cf88051b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('segment_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_ids', sa.JSON(), nullable=True, comment='List of user IDs in this segment'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_segments_restaurant_id'), 'customer_segments', ['restaurant_id'], unique=False)
    op.create_table('delivery_fleet',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('license_plate', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('last_ping', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_fleet_restaurant_id'), 'delivery_fleet', ['restaurant_id'], unique=False)
    op.create_table('global_tenant_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('is_dynamic_pricing_enabled', sa.Boolean(), nullable=True),
    sa.Column('enabled_modules', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.create_table('integration_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('api_secret', sa.String(length=255), nullable=True),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_configs_restaurant_id'), 'integration_configs', ['restaurant_id'], unique=False)
    op.create_table('investor_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_url', sa.String(length=512), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('data_summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investor_reports_restaurant_id'), 'investor_reports', ['restaurant_id'], unique=False)
    op.create_table('kitchen_iot_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_reading', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kitchen_iot_devices_restaurant_id'), 'kitchen_iot_devices', ['restaurant_id'], unique=False)
    op.create_table('tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('qr_code_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_branch_id'), 'tables', ['branch_id'], unique=False)
    op.create_table('payrolls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_bonuses', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_penalties', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_pay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payrolls_user_id'), 'payrolls', ['user_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_item_id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('restaurant_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fleet_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('estimated_arrival', sa.DateTime(), nullable=True),
    sa.Column('route_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['fleet_id'], ['delivery_fleet.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity_required', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bonus_cards', sa.Column('xp_points', sa.Integer(), nullable=False, comment='Gamification XP points'))
    op.add_column('menu_items', sa.Column('ar_model_url', sa.String(length=512), nullable=True, comment='AR Model for AR Menu Experience'))
    op.add_column('menu_items', sa.Column('vr_scene_url', sa.String(length=512), nullable=True, comment='VR Scene for VR Ordering'))
    op.add_column('restaurants', sa.Column('virtual_tour_url', sa.String(length=512), nullable=True, comment='360/VR Virtual Tour URL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'virtual_tour_url')
    op.drop_column('menu_items', 'vr_scene_url')
    op.drop_column('menu_items', 'ar_model_url')
    op.drop_column('bonus_cards', 'xp_points')
    op.drop_table('recipe_ingredients')
    op.drop_table('delivery_routes')
    op.drop_table('support_tickets')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_payrolls_user_id'), table_name='payrolls')
    op.drop_table('payrolls')
    op.drop_index(op.f('ix_tables_branch_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_kitchen_iot_devices_restaurant_id'), table_name='kitchen_iot_devices')
    op.drop_table('kitchen_iot_devices')
    op.drop_index(op.f('ix_investor_reports_restaurant_id'), table_name='investor_reports')
    op.drop_table('investor_reports')
    op.drop_index(op.f('ix_integration_configs_restaurant_id'), table_name='integration_configs')
    op.drop_table('integration_configs')
    op.drop_table('global_tenant_settings')
    op.drop_index(op.f('ix_delivery_fleet_restaurant_id'), table_name='delivery_fleet')
    op.drop_table('delivery_fleet')
    op.drop_index(op.f('ix_customer_segments_restaurant_id'), table_name='customer_segments')
    op.drop_table('customer_segments')
    # ### end Alembic commands ###
