"""Add CRM Finance HR Extended models

Revision ID: 43515047d6d4
Revises: 230b54e56456
Create Date: 2026-06-18 14:49:39.197402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43515047d6d4'
down_revision: Union[str, None] = '230b54e56456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('financial_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('system_name', sa.String(length=100), nullable=False),
    sa.Column('api_credentials', sa.JSON(), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.create_table('recruitment_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('applied_role', sa.String(length=50), nullable=False),
    sa.Column('resume_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('tax_name', sa.String(length=100), nullable=False),
    sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referrer_id', sa.UUID(), nullable=False),
    sa.Column('referred_user_id', sa.UUID(), nullable=True),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('referral_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_table('skill_matrices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True, comment='[{"skill": "Barista", "level": 5}]'),
    sa.Column('last_assessed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('social_media_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('social_account_id', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_media_integrations_user_id'), 'social_media_integrations', ['user_id'], unique=False)
    op.create_table('staff_trainings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_trainings_user_id'), 'staff_trainings', ['user_id'], unique=False)
    op.add_column('notifications', sa.Column('channels', sa.JSON(), nullable=True, comment='Sent channels: ["PUSH", "SMS", "WHATSAPP"]'))
    op.add_column('orders', sa.Column('is_group_order', sa.Boolean(), nullable=True, comment='Is this a group/split bill order'))
    op.add_column('orders', sa.Column('parent_order_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'orders', ['parent_order_id'], ['id'], ondelete='CASCADE')
    op.add_column('recipes', sa.Column('video_url', sa.String(length=512), nullable=True, comment='Video tutorial for chef'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'video_url')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'parent_order_id')
    op.drop_column('orders', 'is_group_order')
    op.drop_column('notifications', 'channels')
    op.drop_index(op.f('ix_staff_trainings_user_id'), table_name='staff_trainings')
    op.drop_table('staff_trainings')
    op.drop_index(op.f('ix_social_media_integrations_user_id'), table_name='social_media_integrations')
    op.drop_table('social_media_integrations')
    op.drop_table('skill_matrices')
    op.drop_table('referrals')
    op.drop_table('tax_rules')
    op.drop_table('recruitment_candidates')
    op.drop_table('financial_integrations')
    op.drop_table('currencies')
    # ### end Alembic commands ###
